services:
  # MySQL service
  db:
    image: mysql:latest
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d # Volume pour l'initialisation de la base de données - Ne pas laisser d'instruction CREATE DATABASE dans le fichier SQL
      - ./sql:/var/lib/mysql # Volume pour stocker la base de données
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress_user
      MYSQL_PASSWORD: wordpress_password
    ports:
      - "33006:3306"

  # phpMyAdmin service
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root_password # Le même mot de passe que celui défini pour MYSQL_ROOT_PASSWORD dans le service MySQL

  # WordPress service
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "8000:80"
    volumes:
      - ./wordpress:/var/www/html # Générer le fichier .htaccess manuellement + Modifier les valeurs du wp-config.php
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress_user
      WORDPRESS_DB_PASSWORD: wordpress_password
      WORDPRESS_DB_NAME: wordpress
