version: '3'

services:
  # MySQL service
  db:
    image: mysql:5.7
    volumes:
      - ./sql:/docker-entrypoint-initdb.d # Ne pas laisser d'instruction CREATE DATABASE dans le fichier SQL
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress_user
      MYSQL_PASSWORD: wordpress_password
    ports:
      - "33006:3306"

  # WordPress service
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "8000:80"
    volumes:
      - ./wordpress:/var/www/html # Générer le fichier .htaccess manuellement + Modifier les valeurs du wp-config.php
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress_user
      WORDPRESS_DB_PASSWORD: wordpress_password
      WORDPRESS_DB_NAME: wordpress
